### ISSUE TITLE
Property migration is not fully implemented

### ISSUE THREAD

**Issue by rot1024** [reearth/reearth#240]
Property migration at the field level works, but migration at the group level is not implemented, and if a group is changed or deleted, the property may break (no longer conform to the schema).

Example: Migrating

```yaml
propertySchema:
  groups:
    id: "xxx",
    fields: [{ id: "yyy", type: "string" }]
```

to

```yaml
propertySchema:
  groups:
    id: "xxx",
    isList: true, // changed
    fields: [{ id: "yyy", type: "string" }]
```

fails and properties break (they are no longer conform to the new schema)

## Implementation items

- Changing `isList` of a property schema group
   - false -> true: The group should be the first item of a new group list
   - true -> false: The first item of the group list should be a new group
- Deleting a property schema group and group list: Related groups and group lists should be deleted 
- Property fields that value cast is failed should be deleted (currently remains)
